# This is a basic workflow to help you get started with Actions

name: Deploy Template

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
       
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: allenevans/set-env@v1.0.0
      with:
        ADMIN_PASSWORD: 'mypass'
        ADMIN_USERNAME: 'myuser'
        APIM_EMAIL: 'someemail@someemail.com'
        APIM_NAME: 'karlrisstestapim'
  
    # Deploy ARM Template
    - uses: whiteducksoftware/azure-arm-action-js@v3
      with:
        # Provide the name of a resource group.
        resourceGroupName: testdeploy
        # Specify the path to the Azure Resource Manager template.
        templateLocation: ./azuredeploy.json
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).
        deploymentMode: Incremental
        # Specifies the name of the resource group deployment to create.
        deploymentName: TestDeployment
        # Supply deployment parameter values.
        parameters: ./azuredeploy.parameters.json
          adminPassword=${ADMIN_PASSWORD}-overriden
          adminUsername=${ADMIN_USERNAME}-overriden
          apimEmail=${APIM_EMAIL}-overriden
          apimname=${APIM_NAME}-overriden      
